// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiteofgjfowphtchibwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpdGVvZmdqZm93cGh0Y2hpYndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjU1ODgsImV4cCI6MjA2NDY0MTU4OH0.uq-TSv31ki1bfkXYEPt69xJ932rKz-2XIcMupAZVCvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);